services:
  - type: web
    name: muroro-livestock
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_NHOST_SUBDOMAIN
        value: vvbfqblnymvqisooxtft
      - key: VITE_NHOST_REGION
        value: eu-west-2
